
name: Check and test the source code
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.16.8'
          cache: true
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test
      - name: Version up
        run: |
          git config --local user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --local user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          sh shell_script/version_auto_increment.sh
  wait:
    name: Check the source code
    runs-on: ubuntu-latest
    needs: [
      test
    ]
    if: ${{ always() && !cancelled() && needs.test.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.16.8'
          cache: true
      - name: Install packages
        run: flutter pub get

