
name: Check and test the source code
on:
  pull_request:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.16.8'
          cache: true
      - name: Git config
        run: |
          git remote set-url origin https://github-actions:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --local user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git fetch origin ${{ github.event.pull_request.head.ref }} 
          git switch ${{ github.event.pull_request.head.ref }}
      - name: Version up
        run: |
          perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' pubspec.yaml
          git add pubspec.yaml
          git commit -m "Bump version to $version" pubspec.yaml
      - name: Push
        run: |
          git branch
          git push origin ${{ github.event.pull_request.head.ref }}
          git tag $version
          git push origin $version
  wait:
    name: Check the source code
    runs-on: ubuntu-latest
    needs: [
      test
    ]
    if: ${{ always() && !cancelled() && needs.test.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.16.8'
          cache: true
      - name: Commit message
        run: echo github.event.head_commit.message


